services:
  hyperhdr:
    image: manu0466/hyperhdr:21.0.0.0
    privileged: true
    volumes:
      - ./data:/root/.hyperhdr
    devices:
      - /dev/video0:/dev/video0
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - "8090:8090"
      - "19444:19444"
    restart: unless-stopped

